### PR TITLE
Add .glide to skipped dirs and add info about vendoring repo

### PR DESCRIPTION
**Pull request by duglin**
Signed-off-by: Doug Davis <dug@us.ibm.com>

### CODE REVIEW

**Comment by eparis** [comment]
Doing this via `vendor`ing means it won't get updates in the consuming repository. Is this really a pattern we want to suggest?

@bgrant0607 @kubernetes/sig-contributor-experience-misc I'm torn...

**Comment by duglin** [comment]
@eparis can you elaborate, what do you mean by it not getting updates in the consuming repo?

**Comment by eparis** [comment]
I mean that if you copy this repo into vendor in the service catalog repo, updates in this repo won't $magically appear in the service catalog repo. A human would have to manually update the Godep/vendor. If instead one uses git submodules then cloning the service catalog repo would also require cloning this repo which would in turn mean that the new combination had all of the updates from here.

I believe use git submodules would mean that the consuming repo would always have the latest and greatest 'repo-infra' in every CI run. Again this would nto be true with Godep/vendor as the only time it would be updated would be by a human...

**Comment by duglin** [comment]
@eparis ah, thanks.  Wouldn't it be best to leave it up to each "using repo" to decide? I mean we can't really stop anyone from choosing to vendor, godep, glide, git-submodule, etc... this repo - the best we can do it let them know about any things to watch out for - like assumptions of dir structure.

**Comment by bgrant0607** [comment]
cc @thockin

**Comment by thockin** [comment]
I don't know much about git subtree, but AIUI, it requires at least one extra git command to checkout and another to "sync to head" yes?

Godep et al won't really handle it, I think.  They expect a) to vendor into `vendor/` and b) that you're vendoring go code.

**Comment by pmorie** [comment]
@bgrant0607 in a vacuum i would prefer subtree, but it has some hiccups with rebase that makes me think vendor/ is okay for now.  Really, there isn't a great solution for this in git.

@thockin subtree doesn't require an additional comment to fetch, but it does have problems merging.

So, TLDR, I'm not really happy with any way to accomplish this in git currently, but since Doug has strong opinions I have delegated this area to him for now.  I think /vendor is a fine way to do things for now since it is as imperfect as any other, but I think we will probably wind up re-evaluating it in the near future.

cc @duglin

**Pull request merged**
