### PR TITLE
bazel 0.27: rename single_file to allow_single_file

### PR DESCRIPTION
**Pull request by justinsb**
Fix to be compatible with bazel 0.27

### CODE REVIEW

**Comment by prestonvanloon** [comment]
Please merge this :)

**Comment by munnerz** [comment]
This appears to be failing on what *looks* like unrelated failures. They are on Travis however, which limits who can restart the job.

Can someone with permissions look into restarting this?

/cc @cblecker @ixdy

**Comment by ixdy** [comment]
/lgtm

I think the travis build might be completely broken, though.

**Comment by fejta** [comment]
This is blocked by https://github.com/kubernetes/repo-infra/issues/117

**Comment by cblecker** [comment]
I'm going to force merge this. I tried to get this working, but this repo is kind of a mess right now. The `//tools:` target is completely broken because a dependant package doesn't exist (likely moved?).

**Pull request merged**
