### PR TITLE
kazel: don't follow symlinks when walking tree

### PR DESCRIPTION
**Pull request by ixdy**
As discussed [on slack](https://kubernetes.slack.com/archives/C5NV3MT97/p1499389296559715), I don't think we need to follow symlinks anymore, assuming we're walking the whole tree.

We apparently needed this functionality to follow symlinks from `vendor/k8s.io` into `staging/k8s.io`, but if we just walk `staging/` this may not be necessary. I'm still validating to see if this actually works.

The motivation is that
* `gazelle` walks the whole tree by default, so it'd be easier to make that work correctly
* some of the other modules in `kazel` (e.g. sourcerer) don't handle symlinks correctly

x-ref https://github.com/kubernetes/kubernetes/issues/47558
/assign @mikedanese @spxtr

### CODE REVIEW

**Comment by spxtr** [comment]
How have you verified that this is okay?

**Comment by ixdy** [comment]
tested by branching from https://github.com/kubernetes/kubernetes/pull/48964, updating kazel to point to this branch/commit, removing the `SrcsDirs` and most of the `SkippedPaths`, and then regenerating: https://github.com/ixdy/kubernetes/tree/update-kazel

**Comment by ixdy** [comment]
any more thoughts on this one?

**Pull request merged**
