### PR TITLE
Remove the buggy bazel check_version function

### PR DESCRIPTION
**Pull request by ixdy**
This function doesn't handle two-digit version numbers like "0.10" correctly. Rather than fix it here, we should just be using the fixed version added to bazelbuild/bazel-skylib in https://github.com/bazelbuild/bazel-skylib/pull/13.

x-ref bazelbuild/bazel#4425

/assign @BenTheElder @mikedanese

### CODE REVIEW

**Comment by BenTheElder** [comment]
Maybe we should hold off on merging this until we've had time for everyone to update their checkouts etc?

**Comment by ixdy** [comment]
I'm hoping nobody is checking out this repo at HEAD. They should be locked on a commit which still includes this function.

**Comment by BenTheElder** [comment]
Hmm @ixdy does this repo not have merge automation?

**Comment by ixdy** [comment]
It does not. We probably need to convert the travis checks to prow before we can do that, though, right?

I was also considering waiting until bumping `rules_go` (which needs some changes to `go_genrule`) before merging this PR.

**Comment by BenTheElder** [comment]
> It does not. We probably need to convert the travis checks to prow before we can do that, though, right?

We shouldn't need to, tide should work with all checks (?)

> I was also considering waiting until bumping rules_go (which needs some changes to go_genrule) before merging this PR.

SGTM

**Comment by ixdy** [comment]
Does tide know how to retrigger travis checks?

**Comment by BenTheElder** [comment]
> Does tide know how to retrigger travis checks?

Ah, no, it will just ignore them as long as they are green 🤷‍♂️

**Comment by ixdy** [comment]
it occurs to me that tide not re-triggering travis is no worse than the status quo, so let's get tide enabled here.

**Pull request merged**
