### PR TITLE
Import gazel into kubernetes/repo-infra as kazel

### PR DESCRIPTION
**Pull request by ixdy**
First step of https://github.com/kubernetes/kubernetes/issues/47558: I'm importing `gazel` as-is, with the full git history.

Next steps will involve pulling the rules_go functionality out of `kazel` and making sure it can interoperate with `gazelle`.

### CODE REVIEW

**Comment by ixdy** [comment]
I suspect the clabot is unhappy about @lstoll and @dixudx's commits.

**Comment by lstoll** [comment]
@ixdy I just signed the CLA.

**Comment by ixdy** [comment]
@lstoll thanks!

**Comment by ixdy** [comment]
checks all pass, finally.

**Comment by spxtr** [comment]
What's the advantage of keeping a fork here rather than just developing in the main gazel repo? I was thinking it might be possible to add a flag that makes it skip doing go rules.

How are we going to version this?

**Comment by ixdy** [comment]
It's always felt a little awkward to me that we depend on @mikedanese's personal repo rather than one of the kubernetes repos. Given that we're likely to depend on <s>`gazel`</s> `kazel` long-term, it seems like we should make it more official.

Also, I want to eliminate the `gazel` vs. `gazelle` confusion, hence the rename.

For versioning we can probably do something similar to what's been done with `gazel`, tagging releases in the repo-infra repo. We could also potentially build a docker image or something like that.

**Comment by mikedanese** [comment]
lgtm if someone gives me write access to this repo

**Comment by ixdy** [comment]
https://github.com/orgs/kubernetes/teams/repo-infra-maintainers/members

/me tags @spxtr

**Comment by spxtr** [comment]
Done.

**Comment by ixdy** [comment]
Does @mikedanese's lgtm count as "I can merge"? did I sufficiently answer your concerns, @spxtr?

**Comment by ixdy** [comment]
(side note: I find it slightly ironic that the `repo-infra` repo doesn't have the right label colors.)

**Pull request merged**
