### PR TITLE
adding depstat

### PR DESCRIPTION
**Pull request by RinkiyaKeDad**
Hey folks! 

`depstat` is a tool that will be run as part of the Kubernetes CI pipeline and will help to evaluate the dependency changes which come along with PRs to the k/k repository.

We have completed v1 of the tool and have tested it out with the k/k repository too.

Link to the issue on k/k repo: https://github.com/kubernetes/kubernetes/issues/98698

PR testing `depstat` with the k/k repo: https://github.com/kubernetes/kubernetes/pull/100792

We were hoping to host the code for `depstat` in this repository.
I've also sent a note about the same to the sig-release mailing list. You can also see a demo in the gif attached in the project [README](https://github.com/RinkiyaKeDad/repo-infra/tree/master/cmd/depstat). Please let us know your thoughts on this :)

### CODE REVIEW

**Comment by dims** [comment]
@RinkiyaKeDad please see the broken CI jobs, you may have to run the update script in `hack/` directory for bazel and deps at least to get this green.

**Comment by justaugustus** [comment]
@RinkiyaKeDad @dims -- It's wonderful to see this work happening!

To move this forward, could we instead work on a [repo donation via this issue template](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-repo&template=repo-create.md&title=)?
Moving `depstat` into this repo will create some dependencies on bazel for ongoing maintenance that ideally we'd like to avoid.

cc: @kubernetes/release-engineering @kubernetes/sig-release-leads

**Comment by justaugustus** [comment]
(A future option would be to integrate this with [zeitgeist](https://github.com/kubernetes-sigs/zeitgeist), but let's get the code into the project first and consider that as a potential follow-up.)

**Comment by dims** [comment]
@justaugustus there was a request to sig-release mailing list as well fyi - https://groups.google.com/g/kubernetes-sig-release/c/fU9KV5jqV5g/m/EfbtE9NICAAJ

thanks for the guidance. @RinkiyaKeDad Arsh, looks like we have the guidance from release folks now for a new repo.

**Comment by justaugustus** [comment]
> @justaugustus there was a request to sig-release mailing list as well fyi - https://groups.google.com/g/kubernetes-sig-release/c/fU9KV5jqV5g/m/EfbtE9NICAAJ

Yep, yep. I think we're all still combing through the inboxes post-v1.21 🙃
Let's circle back there to update everyone once the repo is migrated in.

> thanks for the guidance. @RinkiyaKeDad Arsh, looks like we have the guidance from release folks now for a new repo.

Awesome. I'm going to close this PR out, but please tag @kubernetes/sig-release-leads in the repo migration request and we'll approve and help get CI wired up. 💕

/close

**Pull request closed without merging**
