### PR TITLE
Update common rules to their latest versions

### PR DESCRIPTION
**Pull request by fejta**
/assign @mikedanese @justaugustus @BenTheElder 
/hold

Superset of https://github.com/kubernetes/repo-infra/pull/188

### CODE REVIEW

**Comment by fejta** [comment]
off by one error

**Comment by BenTheElder** [comment]
apparently failing due to something with AIX :upside_down_face:

**Comment by fejta** [comment]
Yeah the next version of rules_go apparently adds the AIX stuff

**Pull request merged**
