### PR TITLE
WORKSPACE: Don't force go version in `configure()` directive

### PR DESCRIPTION
**Pull request by justaugustus**
Signed-off-by: Stephen Augustus <foo@auggie.dev>

/assign @hasheddan @cpanato @puerco 
ref: https://github.com/kubernetes/release/issues/1984, https://kubernetes.slack.com/archives/C2C40FMNF/p1617783514267200?thread_ts=1617365695.206200&cid=C2C40FMNF, https://kubernetes.slack.com/archives/GKEA5EL67/p1618421701018300?thread_ts=1618419664.017100&cid=GKEA5EL67

### CODE REVIEW

**Review by hasheddan — COMMENTED** [review]
@justaugustus know what caused the large go.sum changes?

**Comment by justaugustus** [comment]
> @justaugustus know what caused the large go.sum changes?

Side-effect from my local env running go1.16.3.
I reset the file and re-ran `./hack/update-dep.sh` with go1.15.11, which drops that diff.

**Review by hasheddan — APPROVED** [review]
/lgtm

**Comment by justaugustus** [comment]
Filed https://github.com/kubernetes/repo-infra/issues/239 for the `go mod tidy` check.

**Pull request merged**
